apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  externalIPs:
  - 45.43.30.19
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: avorion-27000-tcp
    port: 27000
    protocol: TCP
    targetPort: 27000
  - name: avorion-27003-udp
    port: 27003
    protocol: UDP
    targetPort: 27003
  - name: avorion-27020-udp
    port: 27020
    protocol: UDP
    targetPort: 27020
  - name: terraria-7777-tcp
    port: 7777
    protocol: TCP
    targetPort: 7777
  - name: terraria-7777-udp
    port: 7777
    protocol: UDP
    targetPort: 7777
  selector:
    app: ingress-nginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
