# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraria
  namespace: games
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: terraria
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: terraria
    spec:
      containers:
      - env:
        - name: world
          value: Erf.wld
        image: beardedio/terraria:vanilla-1.4.0.2
        imagePullPolicy: Always
        name: terraria
        ports:
        - name: main-tcp
          containerPort: 7777
          protocol: TCP
        - name: main-udp
          containerPort: 7777
          protocol: UDP
        resources: {}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /config
          name: nfs-root
        - mountPath: /root/.local/share/Terraria/Worlds
          name: nfs-worlds
      dnsPolicy: ClusterFirst
      nodeSelector:
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      volumes:
      - name: nfs-root
        nfs:
          path: /nfsfileshare/games/terraria
          server: 172.16.100.13
      - name: nfs-worlds
        nfs:
          path: /nfsfileshare/games/terraria/worlds
          server: 172.16.100.13