apiVersion: v1
kind: Service
metadata:
  name: terraria-service
  namespace: games
spec:
  ports:
  - name: main-tcp
    port: 7777
    protocol: TCP
  - name: main-udp
    port: 7777
    protocol: UDP
  selector:
    app: terraria
  sessionAffinity: None
  type: ClusterIP